
project_id = "smooniqpqenxdbkceppn"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_strong_password = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
otp_token_lifetime = 300

[functions]
port = 54328

[functions.handle-invitation]
verify_jwt = true
