-- This function is no longer needed as we're using direct queries instead.
-- Keeping this file with a comment to maintain file structure.
-- The function was intended to get property names by IDs without causing recursion.
